services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - transactional_db
      - analytical_db
    environment:
      FLASK_ENV: development
      DB_URL: postgres://postgres:postgres@transactional_db:5432/appdb_transactional
      DB2_URL: postgres://postgres:postgres@analytical_db:5432/appdb_analytical
    volumes:
      - .:/app
      - /app/.venv

  transactional_db:
    image: postgres:15
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/var/lib/postgresql/data/pg_hba.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb_transactional
    ports:
      - "5432:5432"
    volumes:
      - pgdata_transactional:/var/lib/postgresql/data
      - ./transactional_db_initialization:/docker-entrypoint-initdb.d
      - ./postgres_wal/archiving.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres_wal/wal_archive:/var/lib/postgresql/wal_archive

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d appdb_transactional"]
        interval: 5s
        timeout: 5s
        retries: 5

  analytical_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb_analytical
    ports:
      - "5433:5432"
    volumes:
      - pgdata_analytical:/var/lib/postgresql/data
      - ./analytical_db_initialization:/docker-entrypoint-initdb.d

    depends_on:
      transactional_db:
        condition: service_healthy
        
  backup:
    image: postgres:15
    depends_on:
      - transactional_db
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "until pg_isready -h transactional_db -U postgres; do
        echo 'Waiting for transactional_db...';
        sleep 2;
      done;
      sleep 5;
      echo 'Starting base backup';
      PGPASSWORD=replicator_password pg_basebackup -h transactional_db -U replicator -D /backup/backup_$(date +%Y%m%d_%H%M%S) -Ft -z -P -v;
      echo 'Backup completed';"
    volumes:
      - ./pg_basebackups:/backup
      - ./postgres_wal/wal_archive:/var/lib/postgresql/wal_archive:ro

volumes:
  pgdata_transactional:
  pgdata_analytical:
