services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - transactional_db
      - analytical_db
    environment:
      FLASK_ENV: development
      DB_URL: postgresql://postgres:postgres@transactional_db:5432/appdb_transactional
      BACKUP_URL: postgresql://postgres:postgres@standby_db:5432/appdb_transactional
      DB2_URL: postgresql://postgres:postgres@analytical_db:5432/appdb_analytical
    volumes:
      - .:/app
      - /app/.venv

  transactional_db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb_transactional
    ports:
      - "5432:5432"
    volumes:
      - pgdata_transactional:/var/lib/postgresql/data
      - ./transactional_db_initialization:/docker-entrypoint-initdb.d
      - ./postgres_wal/archiving.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres_wal/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - wal_archive_volume:/var/lib/postgresql/wal_archive

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d appdb_transactional"]
        interval: 5s
        timeout: 5s
        retries: 5

  analytical_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb_analytical
    ports:
      - "5433:5432"
    volumes:
      - pgdata_analytical:/var/lib/postgresql/data
      - ./analytical_db_initialization:/docker-entrypoint-initdb.d

    depends_on:
      transactional_db:
        condition: service_healthy

  wal_sync:
    image: postgres:15
    restart: always
    depends_on:
      transactional_db:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "echo 'WAL sync service started';
      while true; do
        echo 'Syncing WAL files to local directory...';
        cp -rn /var/lib/postgresql/wal_archive/* /backup/ 2>/dev/null || true;
        file_count=$(ls -1 /backup 2>/dev/null | wc -l);
        echo \"Currently synced: $file_count WAL files\";
        sleep 30;
      done"
    volumes:
      - wal_archive_volume:/var/lib/postgresql/wal_archive:ro
      - ./postgres_wal/wal_archive_local:/backup

  standby_db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    volumes:
      - pgdata_standby:/var/lib/postgresql/data
      - ./pg_basebackups:/pg_basebackups
      - ./postgres_wal/wal_archive_local:/var/lib/postgresql/wal_archive
      - ./postgres_wal/init_standby.sh:/init_standby.sh:ro
    depends_on:
      transactional_db:
        condition: service_healthy
    user: root
    command: bash -c "chown -R postgres:postgres /var/lib/postgresql/wal_archive 2>/dev/null || true; chmod -R 744 /var/lib/postgresql/wal_archive 2>/dev/null || true; gosu postgres bash -c '/init_standby.sh && exec postgres'"

volumes:
  pgdata_transactional:
  pgdata_analytical:
  wal_archive_volume:
  pgdata_standby: